### ISSUE TITLE
[FR] Add the ability to silently ignore a request to open a browser

### ISSUE THREAD

**Issue by claudio-salvio** [aloneguid/bt#77]
Hi @aloneguid 

Please add the ability to **silently ignore a request to open a browser**.
It would be very useful to avoid the effects of certain annoying applications that open links without asking the user's permission.
These applications usually open links in the browser by default, although this is not always the case.

I believe that these unwanted attempts could be detected using two tools:

1. a url pattern 
2. detecting the application that triggers the request

In most cases the first mechanism would be sufficient, but I imagine that the second could be useful in some circumstances as well.

For informational purposes only, I think it would be useful if you could activate some notification mechanism (toast message?) or loggin.

🙏 Thank you very much for sharing this useful application with the community. 

Best regards,
Claudio
I 💙 Browser Tammer !

**Comment by YESNLars** [comment]
@claudio-salvio 
This was my solution (in `%APPDATA&\roaming\Browser Tamer\config.yml`) to help (cuz i had same question) you do need to use pwsh 7 if not installed just point `cmd:` to normal pwsh: `"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"`)
```
    cmd: "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
    engine: generic
    management: none
    name: PowerShell
    profiles:
      -
        arg: "\"%url%\""
        icon: "C:\\Program Files\\PowerShell\\7\\pwsh.exe"
        name: Default
        rules:
          -
            loc: url
            value: bing
          -
            loc: url
            value: edge
        user_arg: "*>$null"
        visible: false
```
it adds a browser (hidden in picker) but on these rules (url has bing or edge in it, you can edit other rules in config or gui) acts to open nothing. To make sure the 'hidden in picker' works you do need to disable toast in general (or add:  
```toast:
  border_width: 1
  enabled: false
  visible_seconds: 5```
)
